### ISSUE TITLE
"FFNN_CHARACTERS_MAPPING.pickle" Not found 

### ISSUE THREAD

**Issue by AymanASamyM** [AliOsm/shakkelha#5]
The file named ""FFNN_CHARACTERS_MAPPING.pickle" does not exist in the repo.

**Comment by AliOsm** [comment]
Hello @AymanASamyM, `FFNN_CHARACTERS_MAPPING.pickle` file was renamed to `FFNN_SMALL_CHARACTERS_MAPPING.pickle`, which can be found in [constants](https://github.com/AliOsm/shakkelha/tree/master/helpers/constants) folder.

Also, can you please mention the code that caused the file not found error?

**Comment by AymanASamyM** [comment]
prepare_feed_forward_data.py

**Comment by AliOsm** [comment]
I updated the file name in the code.
